import { describe, expect, it } from 'vitest'
import { Lits } from '../../../../Lits/Lits'

const lits = new Lits()
describe('combinatorial', () => {
  describe('c:divisible-by?', () => {
    it('should return true if divisible by', () => {
      expect(lits.run('c:divisible-by?(2, 1)')).toEqual(true)
      expect(lits.run('c:divisible-by?(7, 2)')).toEqual(false)
      expect(lits.run('c:divisible-by?(6, 3)')).toEqual(true)
      expect(lits.run('c:divisible-by?(8, 4)')).toEqual(true)
      expect(lits.run('c:divisible-by?(9, 3)')).toEqual(true)
      expect(lits.run('c:divisible-by?(10, 5)')).toEqual(true)
      expect(lits.run('c:divisible-by?(11, 5)')).toEqual(false)
    })
  })
  describe('c:divisors', () => {
    it('should return divisors of a number', () => {
      expect(lits.run('c:divisors(1)')).toEqual([1])
      expect(lits.run('c:divisors(2)')).toEqual([1, 2])
      expect(lits.run('c:divisors(3)')).toEqual([1, 3])
      expect(lits.run('c:divisors(4)')).toEqual([1, 2, 4])
      expect(lits.run('c:divisors(5)')).toEqual([1, 5])
      expect(lits.run('c:divisors(6)')).toEqual([1, 2, 3, 6])
      expect(lits.run('c:divisors(7)')).toEqual([1, 7])
      expect(lits.run('c:divisors(8)')).toEqual([1, 2, 4, 8])
      expect(lits.run('c:divisors(9)')).toEqual([1, 3, 9])
      expect(lits.run('c:divisors(10)')).toEqual([1, 2, 5, 10])
      expect(lits.run('c:divisors(100)')).toEqual([1, 2, 4, 5, 10, 20, 25, 50, 100])
    })
  })
  describe('c:gcd', () => {
    it('should return the gcd of two numbers', () => {
      expect(lits.run('c:gcd(1, 1)')).toEqual(1)
      expect(lits.run('c:gcd(2, 3)')).toEqual(1)
      expect(lits.run('c:gcd(4, 6)')).toEqual(2)
      expect(lits.run('c:gcd(8, 12)')).toEqual(4)
      expect(lits.run('c:gcd(10, 15)')).toEqual(5)
      expect(lits.run('c:gcd(100, 200)')).toEqual(100)
    })
  })
  describe('c:lcm', () => {
    it('should return the lcm of two numbers', () => {
      expect(lits.run('c:lcm(1, 1)')).toEqual(1)
      expect(lits.run('c:lcm(2, 3)')).toEqual(6)
      expect(lits.run('c:lcm(4, 6)')).toEqual(12)
      expect(lits.run('c:lcm(8, 12)')).toEqual(24)
      expect(lits.run('c:lcm(10, 15)')).toEqual(30)
      expect(lits.run('c:lcm(100, 200)')).toEqual(200)
    })
  })
  describe('c:multinomial', () => {
    it('should return the multinomial coefficient of a list of numbers', () => {
      // Basic cases
      expect(lits.run('c:multinomial(1)')).toEqual(1)
      expect(lits.run('c:multinomial(1, 1)')).toEqual(2)
      expect(lits.run('c:multinomial(1, 1, 1)')).toEqual(6)
      expect(lits.run('c:multinomial(2, 3)')).toEqual(10)
      expect(lits.run('c:multinomial(2, 1, 3)')).toEqual(60)

      // Larger numbers
      expect(lits.run('c:multinomial(4, 2, 1)')).toEqual(105)
      expect(lits.run('c:multinomial(5, 5)')).toEqual(252)
      expect(lits.run('c:multinomial(10, 5)')).toEqual(3003)
      expect(lits.run('c:multinomial(3, 4, 5, 6)')).toEqual(514594080)

      // Edge cases
      expect(lits.run('c:multinomial(0, 0)')).toEqual(1) // 0!/0!0! = 1
      expect(lits.run('c:multinomial(0, 0, 0)')).toEqual(1)
      expect(lits.run('c:multinomial(0, 5)')).toEqual(1) // 5!/5!0! = 1
      expect(lits.run('c:multinomial(5, 0)')).toEqual(1) // 5!/5!0! = 1

      // One parameter case
      expect(lits.run('c:multinomial(0)')).toEqual(1)
      expect(lits.run('c:multinomial(5)')).toEqual(1) // 5!/5! = 1

      // Mixed cases
      expect(lits.run('c:multinomial(1, 0, 1)')).toEqual(2)
      expect(lits.run('c:multinomial(2, 0, 2)')).toEqual(6)
    })
  })

  describe('c:amicable?', () => {
    it('should return true if two numbers are amicable', () => {
      expect(lits.run('c:amicable?(220, 284)')).toEqual(true)
      expect(lits.run('c:amicable?(1184, 1210)')).toEqual(true)
      expect(lits.run('c:amicable?(2620, 2924)')).toEqual(true)
      expect(lits.run('c:amicable?(5020, 5564)')).toEqual(true)
      expect(lits.run('c:amicable?(6232, 6368)')).toEqual(true)
      expect(lits.run('c:amicable?(1210, 1184)')).toEqual(true)
      expect(lits.run('c:amicable?(284, 220)')).toEqual(true)
      expect(lits.run('c:amicable?(6, 28)')).toEqual(false)
      expect(lits.run('c:amicable?(12, 28)')).toEqual(false)
      expect(lits.run('c:amicable?(28, 6)')).toEqual(false)
      expect(lits.run('c:amicable?(220, 220)')).toEqual(false)
      expect(lits.run('c:amicable?(1, 1)')).toEqual(false)
      expect(lits.run('c:amicable?(2, 2)')).toEqual(false)
      expect(() => lits.run('c:amicable?(0, 0)')).toThrow()
    })
  })

  describe('c:euler-totient', () => {
    it('should return the euler totient of a number', () => {
      expect(lits.run('c:euler-totient(1)')).toEqual(1)
      expect(lits.run('c:euler-totient(2)')).toEqual(1)
      expect(lits.run('c:euler-totient(3)')).toEqual(2)
      expect(lits.run('c:euler-totient(4)')).toEqual(2)
      expect(lits.run('c:euler-totient(5)')).toEqual(4)
      expect(lits.run('c:euler-totient(6)')).toEqual(2)
      expect(lits.run('c:euler-totient(7)')).toEqual(6)
      expect(lits.run('c:euler-totient(8)')).toEqual(4)
      expect(lits.run('c:euler-totient(9)')).toEqual(6)
      expect(lits.run('c:euler-totient(10)')).toEqual(4)
      expect(lits.run('c:euler-totient(11)')).toEqual(10)
      expect(lits.run('c:euler-totient(12)')).toEqual(4)
      expect(lits.run('c:euler-totient(13)')).toEqual(12)
      expect(lits.run('c:euler-totient(14)')).toEqual(6)
      expect(lits.run('c:euler-totient(15)')).toEqual(8)
      expect(lits.run('c:euler-totient(16)')).toEqual(8)
      expect(lits.run('c:euler-totient(17)')).toEqual(16)
      expect(lits.run('c:euler-totient(18)')).toEqual(6)
      expect(lits.run('c:euler-totient(19)')).toEqual(18)
      expect(lits.run('c:euler-totient(20)')).toEqual(8)
    })
  })

  describe('c:mobius', () => {
    it('should return the mobius function of a number', () => {
      expect(lits.run('c:mobius(1)')).toEqual(1)
      expect(lits.run('c:mobius(2)')).toEqual(-1)
      expect(lits.run('c:mobius(3)')).toEqual(-1)
      expect(lits.run('c:mobius(4)')).toEqual(0)
      expect(lits.run('c:mobius(5)')).toEqual(-1)
      expect(lits.run('c:mobius(6)')).toEqual(1)
      expect(lits.run('c:mobius(7)')).toEqual(-1)
      expect(lits.run('c:mobius(8)')).toEqual(0)
      expect(lits.run('c:mobius(9)')).toEqual(0)
      expect(lits.run('c:mobius(10)')).toEqual(1)
      expect(lits.run('c:mobius(11)')).toEqual(-1)
      expect(lits.run('c:mobius(12)')).toEqual(0)
      expect(lits.run('c:mobius(13)')).toEqual(-1)
      expect(lits.run('c:mobius(14)')).toEqual(1)
      expect(lits.run('c:mobius(15)')).toEqual(1)
      expect(lits.run('c:mobius(16)')).toEqual(0)
      expect(lits.run('c:mobius(17)')).toEqual(-1)
      expect(lits.run('c:mobius(18)')).toEqual(0)
      expect(lits.run('c:mobius(19)')).toEqual(-1)
      expect(lits.run('c:mobius(20)')).toEqual(0)
      expect(lits.run('c:mobius(21)')).toEqual(1)
      expect(lits.run('c:mobius(22)')).toEqual(1)
      expect(lits.run('c:mobius(23)')).toEqual(-1)
      expect(lits.run('c:mobius(24)')).toEqual(0)
      expect(lits.run('c:mobius(25)')).toEqual(0)
      expect(lits.run('c:mobius(30)')).toEqual(-1)
      expect(lits.run('c:möbius(42)')).toEqual(-1)
      expect(lits.run('c:möbius(60)')).toEqual(0)
      expect(lits.run('c:möbius(75)')).toEqual(0)
      expect(lits.run('c:möbius(98)')).toEqual(0)
      expect(lits.run('c:möbius(105)')).toEqual(-1)
      expect(lits.run('c:möbius(210)')).toEqual(1)
      expect(lits.run('c:möbius(997)')).toEqual(-1)
      expect(lits.run('c:möbius(999)')).toEqual(0)
      expect(lits.run('c:möbius(1000)')).toEqual(0)
      expect(lits.run('c:möbius(2310)')).toEqual(-1)
      expect(lits.run('c:möbius(30030)')).toEqual(1)
    })
  })
  describe('c:mertens', () => {
    it('should return the mertens function of a number', () => {
      expect(lits.run('c:mertens(1)')).toEqual(1)
      expect(lits.run('c:mertens(2)')).toEqual(0)
      expect(lits.run('c:mertens(3)')).toEqual(-1)
      expect(lits.run('c:mertens(4)')).toEqual(-1)
      expect(lits.run('c:mertens(5)')).toEqual(-2)
      expect(lits.run('c:mertens(6)')).toEqual(-1)
      expect(lits.run('c:mertens(7)')).toEqual(-2)
      expect(lits.run('c:mertens(8)')).toEqual(-2)
      expect(lits.run('c:mertens(9)')).toEqual(-2)
      expect(lits.run('c:mertens(10)')).toEqual(-1)
      expect(lits.run('c:mertens(11)')).toEqual(-2)
      expect(lits.run('c:mertens(12)')).toEqual(-2)
      expect(lits.run('c:mertens(13)')).toEqual(-3)
      expect(lits.run('c:mertens(14)')).toEqual(-2)
      expect(lits.run('c:mertens(15)')).toEqual(-1)
      expect(lits.run('c:mertens(16)')).toEqual(-1)
      expect(lits.run('c:mertens(17)')).toEqual(-2)
      expect(lits.run('c:mertens(18)')).toEqual(-2)
      expect(lits.run('c:mertens(19)')).toEqual(-3)
      expect(lits.run('c:mertens(20)')).toEqual(-3)
      expect(lits.run('c:mertens(21)')).toEqual(-2)
      expect(lits.run('c:mertens(22)')).toEqual(-1)
      expect(lits.run('c:mertens(23)')).toEqual(-2)
      expect(lits.run('c:mertens(24)')).toEqual(-2)
      expect(lits.run('c:mertens(25)')).toEqual(-2)
      expect(lits.run('c:mertens(30)')).toEqual(-3)
      expect(lits.run('c:mertens(42)')).toEqual(-2)
      expect(lits.run('c:mertens(60)')).toEqual(-1)
      expect(lits.run('c:mertens(75)')).toEqual(-3)
      expect(lits.run('c:mertens(98)')).toEqual(1)
    })
  })
  describe('c:sigma', () => {
    it('should return the sigma function of a number', () => {
      expect(lits.run('c:sigma(1)')).toEqual(1)
      expect(lits.run('c:sigma(2)')).toEqual(3)
      expect(lits.run('c:sigma(3)')).toEqual(4)
      expect(lits.run('c:sigma(4)')).toEqual(7)
      expect(lits.run('c:sigma(5)')).toEqual(6)
      expect(lits.run('c:sigma(6)')).toEqual(12)
      expect(lits.run('c:sigma(7)')).toEqual(8)
      expect(lits.run('c:sigma(8)')).toEqual(15)
      expect(lits.run('c:sigma(9)')).toEqual(13)
      expect(lits.run('c:sigma(10)')).toEqual(18)
      expect(lits.run('c:sigma(11)')).toEqual(12)
      expect(lits.run('c:sigma(12)')).toEqual(28)
      expect(lits.run('c:sigma(13)')).toEqual(14)
      expect(lits.run('c:sigma(14)')).toEqual(24)
      expect(lits.run('c:sigma(15)')).toEqual(24)
      expect(lits.run('c:sigma(16)')).toEqual(31)
      expect(lits.run('c:sigma(17)')).toEqual(18)
      expect(lits.run('c:sigma(18)')).toEqual(39)
      expect(lits.run('c:sigma(19)')).toEqual(20)
      expect(lits.run('c:sigma(20)')).toEqual(42)
    })
  })
  describe('c:carmichael-lambda', () => {
    it('should return the carmichael lambda of a number', () => {
      expect(lits.run('c:carmichael-lambda(1)')).toEqual(1)
      expect(lits.run('c:carmichael-lambda(2)')).toEqual(1)
      expect(lits.run('c:carmichael-lambda(3)')).toEqual(2)
      expect(lits.run('c:carmichael-lambda(4)')).toEqual(2)
      expect(lits.run('c:carmichael-lambda(5)')).toEqual(4)
      expect(lits.run('c:carmichael-lambda(6)')).toEqual(2)
      expect(lits.run('c:carmichael-lambda(7)')).toEqual(6)
      expect(lits.run('c:carmichael-lambda(8)')).toEqual(2)
      expect(lits.run('c:carmichael-lambda(9)')).toEqual(6)
      expect(lits.run('c:carmichael-lambda(10)')).toEqual(4)
      expect(lits.run('c:carmichael-lambda(11)')).toEqual(10)
      expect(lits.run('c:carmichael-lambda(12)')).toEqual(2)
      expect(lits.run('c:carmichael-lambda(13)')).toEqual(12)
      expect(lits.run('c:carmichael-lambda(14)')).toEqual(6)
      expect(lits.run('c:carmichael-lambda(15)')).toEqual(4)
      expect(lits.run('c:carmichael-lambda(16)')).toEqual(4)
      expect(lits.run('c:carmichael-lambda(17)')).toEqual(16)
    })
  })
  describe('cartesian-product', () => {
    it('should return the cartesian product of two or many lists', () => {
      expect(lits.run('c:cartesian-product([1, 2], [3, 4])')).toEqual([[1, 3], [1, 4], [2, 3], [2, 4]])
      expect(lits.run('c:cartesian-product([1, 2], [])')).toEqual([])
      expect(lits.run('c:cartesian-product([], [3, 4])')).toEqual([])
      expect(lits.run('c:cartesian-product([], [])')).toEqual([])
      expect(lits.run('c:cartesian-product([1, 2], [3, 4], [5, 6])')).toEqual([[1, 3, 5], [1, 3, 6], [1, 4, 5], [1, 4, 6], [2, 3, 5], [2, 3, 6], [2, 4, 5], [2, 4, 6]])
    })
  })
  describe('c:perfect-power', () => {
    it('should return tuple representing powers from number', () => {
      expect(lits.run('c:perfect-power(1)')).toEqual([1, 2])
      expect(lits.run('c:perfect-power(2)')).toEqual(null)
      expect(lits.run('c:perfect-power(4)')).toEqual([2, 2])
      expect(lits.run('c:perfect-power(8)')).toEqual([2, 3])
      expect(lits.run('c:perfect-power(9)')).toEqual([3, 2])
      expect(lits.run('c:perfect-power(16)')).toEqual([4, 2])
      expect(lits.run('c:perfect-power(27)')).toEqual([3, 3])
      expect(lits.run('c:perfect-power(32)')).toEqual([2, 5])
      expect(lits.run('c:perfect-power(64)')).toEqual([8, 2])
      expect(lits.run('c:perfect-power(81)')).toEqual([9, 2])
      expect(lits.run('c:perfect-power(100)')).toEqual([10, 2])
      expect(lits.run('c:perfect-power(121)')).toEqual([11, 2])
      expect(lits.run('c:perfect-power(125)')).toEqual([5, 3])
      expect(lits.run('c:perfect-power(128)')).toEqual([2, 7])
      expect(lits.run('c:perfect-power(729)')).toEqual([27, 2])
      expect(lits.run('c:perfect-power(1000)')).toEqual([10, 3])
      expect(lits.run('c:perfect-power(1024)')).toEqual([32, 2])
      expect(lits.run('c:perfect-power(1331)')).toEqual([11, 3])
      expect(lits.run('c:perfect-power(4096)')).toEqual([64, 2])
      expect(lits.run('c:perfect-power(6561)')).toEqual([81, 2])
    })
  })
  describe('c:mod-exp', () => {
    it('should return the modular exponentiation of a number', () => {
      expect(lits.run('c:mod-exp(2, 3, 5)')).toEqual(3)
      expect(lits.run('c:mod-exp(3, 4, 7)')).toEqual(4)
      expect(lits.run('c:mod-exp(5, 6, 11)')).toEqual(5)
      expect(lits.run('c:mod-exp(7, 8, 13)')).toEqual(3)
      expect(lits.run('c:mod-exp(9, 10, 17)')).toEqual(13)
      expect(lits.run('c:mod-exp(11, 12, 19)')).toEqual(1)
      expect(lits.run('c:mod-exp(13, 14, 23)')).toEqual(12)
      expect(lits.run('c:mod-exp(15, 16, 29)')).toEqual(7)
      expect(lits.run('c:mod-exp(4, 13, 497)')).toEqual(445)
    })
  })
  describe('c:mod-inv', () => {
    it('should return the modular inverse of a number', () => {
      expect(lits.run('c:mod-inv(2, 3)')).toEqual(2)
      expect(lits.run('c:mod-inv(3, 7)')).toEqual(5)
      expect(lits.run('c:mod-inv(4, 11)')).toEqual(3)
      expect(lits.run('c:mod-inv(5, 13)')).toEqual(8)
      expect(lits.run('c:mod-inv(6, 17)')).toEqual(3)
      expect(lits.run('c:mod-inv(7, 19)')).toEqual(11)
      expect(lits.run('c:mod-inv(8, 23)')).toEqual(3)
      expect(lits.run('c:mod-inv(9, 29)')).toEqual(13)
    })
  })
  describe('extended-gcd', () => {
    it('should return the extended gcd of two numbers', () => {
      expect(lits.run('c:extended-gcd(1, 1)')).toEqual([1, 0, 1])
      expect(lits.run('c:extended-gcd(2, 3)')).toEqual([1, -1, 1])
      expect(lits.run('c:extended-gcd(4, 6)')).toEqual([2, -1, 1])
      expect(lits.run('c:extended-gcd(8, 12)')).toEqual([4, -1, 1])
      expect(lits.run('c:extended-gcd(10, 15)')).toEqual([5, -1, 1])
      expect(lits.run('c:extended-gcd(100, 200)')).toEqual([100, 1, 0])
    })
  })
  describe('c:chinese-remainder', () => {
    it('should return the chinese remainder of a list of numbers', () => {
      expect(lits.run('c:chinese-remainder([2, 3], [3, 5])')).toEqual(8)
      expect(lits.run('c:chinese-remainder([2, 3], [3, 5])')).toEqual(8)
      expect(lits.run('c:chinese-remainder([1, 2, 3], [2, 3, 5])')).toEqual(23)
    })
  })
})
