import { describe, expect, it } from 'vitest'
import { Lits } from '../../../../Lits/Lits'

const lits = new Lits()
describe('divisors', () => {
  describe('n:divisors', () => {
    it('should return divisors of a number', () => {
      expect(lits.run('n:divisors(1)')).toEqual([1])
      expect(lits.run('n:divisors(2)')).toEqual([1, 2])
      expect(lits.run('n:divisors(3)')).toEqual([1, 3])
      expect(lits.run('n:divisors(4)')).toEqual([1, 2, 4])
      expect(lits.run('n:divisors(5)')).toEqual([1, 5])
      expect(lits.run('n:divisors(6)')).toEqual([1, 2, 3, 6])
      expect(lits.run('n:divisors(7)')).toEqual([1, 7])
      expect(lits.run('n:divisors(8)')).toEqual([1, 2, 4, 8])
      expect(lits.run('n:divisors(9)')).toEqual([1, 3, 9])
      expect(lits.run('n:divisors(10)')).toEqual([1, 2, 5, 10])
      expect(lits.run('n:divisors(100)')).toEqual([1, 2, 4, 5, 10, 20, 25, 50, 100])
    })
  })
  describe('n:count-divisors', () => {
    it('should return the number of divisors of a number', () => {
      expect(lits.run('n:count-divisors(1)')).toEqual(1)
      expect(lits.run('n:count-divisors(2)')).toEqual(2)
      expect(lits.run('n:count-divisors(3)')).toEqual(2)
      expect(lits.run('n:count-divisors(4)')).toEqual(3)
      expect(lits.run('n:count-divisors(5)')).toEqual(2)
      expect(lits.run('n:count-divisors(6)')).toEqual(4)
      expect(lits.run('n:count-divisors(7)')).toEqual(2)
      expect(lits.run('n:count-divisors(8)')).toEqual(4)
      expect(lits.run('n:count-divisors(9)')).toEqual(3)
      expect(lits.run('n:count-divisors(10)')).toEqual(4)
      expect(lits.run('n:count-divisors(100)')).toEqual(9)
    })
  })
  describe('n:proper-divisors', () => {
    it('should return proper divisors of a number', () => {
      expect(lits.run('n:proper-divisors(1)')).toEqual([])
      expect(lits.run('n:proper-divisors(2)')).toEqual([1])
      expect(lits.run('n:proper-divisors(3)')).toEqual([1])
      expect(lits.run('n:proper-divisors(4)')).toEqual([1, 2])
      expect(lits.run('n:proper-divisors(5)')).toEqual([1])
      expect(lits.run('n:proper-divisors(6)')).toEqual([1, 2, 3])
      expect(lits.run('n:proper-divisors(7)')).toEqual([1])
      expect(lits.run('n:proper-divisors(8)')).toEqual([1, 2, 4])
      expect(lits.run('n:proper-divisors(9)')).toEqual([1, 3])
      expect(lits.run('n:proper-divisors(10)')).toEqual([1, 2, 5])
      expect(lits.run('n:proper-divisors(100)')).toEqual([1, 2, 4, 5, 10, 20, 25, 50])
    })
  })
  describe('n:count-proper-divisors', () => {
    it('should return the number of proper divisors of a number', () => {
      expect(lits.run('n:count-proper-divisors(1)')).toEqual(0)
      expect(lits.run('n:count-proper-divisors(2)')).toEqual(1)
      expect(lits.run('n:count-proper-divisors(3)')).toEqual(1)
      expect(lits.run('n:count-proper-divisors(4)')).toEqual(2)
      expect(lits.run('n:count-proper-divisors(5)')).toEqual(1)
      expect(lits.run('n:count-proper-divisors(6)')).toEqual(3)
      expect(lits.run('n:count-proper-divisors(7)')).toEqual(1)
      expect(lits.run('n:count-proper-divisors(8)')).toEqual(3)
      expect(lits.run('n:count-proper-divisors(9)')).toEqual(2)
      expect(lits.run('n:count-proper-divisors(10)')).toEqual(3)
      expect(lits.run('n:count-proper-divisors(100)')).toEqual(8)
    })
  })
})
