import type { DatatypeName } from './api'
import type { DatatypeReference } from '.'

export const datatype: Record<DatatypeName, DatatypeReference> = {
  '-type-number': {
    datatype: true,
    clojureDocs: null,
    title: 'number',
    category: 'Datatype',
    linkName: '-type-number',
    description: 'A number',
    examples: [
      '42',
      '3.14',
    ],
  },
  '-type-string': {
    datatype: true,
    clojureDocs: null,
    title: 'string',
    category: 'Datatype',
    linkName: '-type-string',
    description: 'A string',
    examples: [
      '"hello"',
      '""',
    ],
  },
  '-type-object': {
    datatype: true,
    clojureDocs: null,
    title: 'object',
    category: 'Datatype',
    linkName: '-type-object',
    description: 'An object, a collection of key-value pairs where keys are strings',
    examples: [
      '{}',
      '{:a 1 :b 2}',
    ],
  },
  '-type-array': {
    datatype: true,
    clojureDocs: null,
    title: 'array',
    category: 'Datatype',
    linkName: '-type-array',
    description: 'An array, a collection of values',
    examples: [
      '[]',
      '[1 2 3]',
      '[:a nil true]',
    ],
  },
  '-type-boolean': {
    datatype: true,
    clojureDocs: null,
    title: 'boolean',
    category: 'Datatype',
    linkName: '-type-boolean',
    description: 'A boolean',
    examples: [
      'true',
      'false',
    ],
  },
  '-type-function': {
    datatype: true,
    clojureDocs: null,
    title: 'function',
    category: 'Datatype',
    linkName: '-type-function',
    description: 'A function',
    examples: [
      '(fn [x] (+ x 1))',
      '(fn [] 42)',
      '#(+ %1 %2)',
    ],
  },
  '-type-integer': {
    datatype: true,
    clojureDocs: null,
    title: 'integer',
    category: 'Datatype',
    linkName: '-type-integer',
    description: 'An integer',
    examples: [
      '42',
      '-42',
    ],
  },
  '-type-any': {
    datatype: true,
    clojureDocs: null,
    title: 'any',
    category: 'Datatype',
    linkName: '-type-any',
    description: 'Any value',
    examples: [
      '42',
      '"hello"',
      'true',
      'nil',
    ],
  },
  '-type-nil': {
    datatype: true,
    clojureDocs: null,
    title: 'nil',
    category: 'Datatype',
    linkName: '-type-nil',
    description: 'The value nil',
    examples: [
      'nil',
    ],
  },
  '-type-collection': {
    datatype: true,
    clojureDocs: null,
    title: 'collection',
    category: 'Datatype',
    linkName: '-type-collection',
    description: 'A collection, an object, an array or a string',
    examples: [
      '{:foo 42}',
      '[1, 2, 3]',
      '"hello"',
    ],
  },
  '-type-sequence': {
    datatype: true,
    clojureDocs: null,
    title: 'sequence',
    category: 'Datatype',
    linkName: '-type-sequence',
    description: 'A sequence, an array or a string',
    examples: [
      '[1 2 3]',
      '"hello"',
    ],
  },
  '-type-regexp': {
    datatype: true,
    clojureDocs: null,
    title: 'regexp',
    category: 'Datatype',
    linkName: '-type-regexp',
    description: 'A regular expression',
    examples: [
      '(regexp "^\\s*(.*)$")',
      '#"albert"ig',
    ],
  },
  '-type-never': {
    datatype: true,
    clojureDocs: null,
    title: 'never',
    category: 'Datatype',
    linkName: '-type-never',
    description: 'A value that can never be created',
    examples: [
      '(throw "error")',
    ],
  },
}
