import { describe, expect, it } from 'vitest'
import { Lits } from '../../../../../Lits/Lits'
import { LitsError } from '../../../../../errors'

const lits = new Lits()
describe('number theory', () => {
  describe('nth:coprime?', () => {
    it('should return true if two numbers are coprime', () => {
      expect(lits.run('nth:coprime?(1, 1)')).toEqual(true)
      expect(lits.run('nth:coprime?(2, 3)')).toEqual(true)
      expect(lits.run('nth:coprime?(4, 6)')).toEqual(false)
      expect(lits.run('nth:coprime?(8, 12)')).toEqual(false)
      expect(lits.run('nth:coprime?(10, 15)')).toEqual(false)
      expect(lits.run('nth:coprime?(100, 200)')).toEqual(false)
    })
  })
  describe('nth:divisible-by?', () => {
    it('should return true if divisible by', () => {
      expect(lits.run('nth:divisible-by?(2, 1)')).toEqual(true)
      expect(lits.run('nth:divisible-by?(7, 2)')).toEqual(false)
      expect(lits.run('nth:divisible-by?(6, 3)')).toEqual(true)
      expect(lits.run('nth:divisible-by?(8, 4)')).toEqual(true)
      expect(lits.run('nth:divisible-by?(9, 3)')).toEqual(true)
      expect(lits.run('nth:divisible-by?(10, 5)')).toEqual(true)
      expect(lits.run('nth:divisible-by?(11, 5)')).toEqual(false)
      expect(lits.run('nth:divisible-by?(11, 0)')).toEqual(false)
      expect(() => lits.run('nth:divisible-by?(2.5, 0.5)')).toThrow()
    })
  })
  describe('nth:gcd', () => {
    it('should return the gcd of two numbers', () => {
      expect(lits.run('nth:gcd(1, 1)')).toEqual(1)
      expect(lits.run('nth:gcd(2, 3)')).toEqual(1)
      expect(lits.run('nth:gcd(4, 6)')).toEqual(2)
      expect(lits.run('nth:gcd(8, 12)')).toEqual(4)
      expect(lits.run('nth:gcd(10, 15)')).toEqual(5)
      expect(lits.run('nth:gcd(100, 200)')).toEqual(100)
    })
  })
  describe('nth:lcm', () => {
    it('should return the lcm of two numbers', () => {
      expect(lits.run('nth:lcm(1, 1)')).toEqual(1)
      expect(lits.run('nth:lcm(2, 3)')).toEqual(6)
      expect(lits.run('nth:lcm(4, 6)')).toEqual(12)
      expect(lits.run('nth:lcm(8, 12)')).toEqual(24)
      expect(lits.run('nth:lcm(10, 15)')).toEqual(30)
      expect(lits.run('nth:lcm(100, 200)')).toEqual(200)
    })
  })
  describe('nth:multinomial', () => {
    it('should return the multinomial coefficient of a list of numbers', () => {
      // Basic cases
      expect(lits.run('nth:multinomial(1)')).toEqual(1)
      expect(lits.run('nth:multinomial(1, 1)')).toEqual(2)
      expect(lits.run('nth:multinomial(1, 1, 1)')).toEqual(6)
      expect(lits.run('nth:multinomial(2, 3)')).toEqual(10)
      expect(lits.run('nth:multinomial(2, 1, 3)')).toEqual(60)

      // Larger numbers
      expect(lits.run('nth:multinomial(4, 2, 1)')).toEqual(105)
      expect(lits.run('nth:multinomial(5, 5)')).toEqual(252)
      expect(lits.run('nth:multinomial(10, 5)')).toEqual(3003)
      expect(lits.run('nth:multinomial(3, 4, 5, 6)')).toEqual(514594080)

      // Edge cases
      expect(lits.run('nth:multinomial(0, 0)')).toEqual(1) // 0!/0!0! = 1
      expect(lits.run('nth:multinomial(0, 0, 0)')).toEqual(1)
      expect(lits.run('nth:multinomial(0, 5)')).toEqual(1) // 5!/5!0! = 1
      expect(lits.run('nth:multinomial(5, 0)')).toEqual(1) // 5!/5!0! = 1

      // One parameter case
      expect(lits.run('nth:multinomial(0)')).toEqual(1)
      expect(lits.run('nth:multinomial(5)')).toEqual(1) // 5!/5! = 1

      // Mixed cases
      expect(lits.run('nth:multinomial(1, 0, 1)')).toEqual(2)
      expect(lits.run('nth:multinomial(2, 0, 2)')).toEqual(6)
    })
  })

  describe('nth:amicable?', () => {
    it('should return true if two numbers are amicable', () => {
      expect(lits.run('nth:amicable?(220, 284)')).toEqual(true)
      expect(lits.run('nth:amicable?(1184, 1210)')).toEqual(true)
      expect(lits.run('nth:amicable?(2620, 2924)')).toEqual(true)
      expect(lits.run('nth:amicable?(5020, 5564)')).toEqual(true)
      expect(lits.run('nth:amicable?(6232, 6368)')).toEqual(true)
      expect(lits.run('nth:amicable?(1210, 1184)')).toEqual(true)
      expect(lits.run('nth:amicable?(284, 220)')).toEqual(true)
      expect(lits.run('nth:amicable?(6, 28)')).toEqual(false)
      expect(lits.run('nth:amicable?(12, 28)')).toEqual(false)
      expect(lits.run('nth:amicable?(28, 6)')).toEqual(false)
      expect(lits.run('nth:amicable?(220, 220)')).toEqual(false)
      expect(lits.run('nth:amicable?(1, 1)')).toEqual(false)
      expect(lits.run('nth:amicable?(2, 2)')).toEqual(false)
      expect(() => lits.run('nth:amicable?(0, 0)')).toThrow()
    })
  })

  describe('nth:euler-totient', () => {
    it('should return the euler totient of a number', () => {
      expect(lits.run('nth:euler-totient(1)')).toEqual(1)
      expect(lits.run('nth:euler-totient(2)')).toEqual(1)
      expect(lits.run('nth:euler-totient(3)')).toEqual(2)
      expect(lits.run('nth:euler-totient(4)')).toEqual(2)
      expect(lits.run('nth:euler-totient(5)')).toEqual(4)
      expect(lits.run('nth:euler-totient(6)')).toEqual(2)
      expect(lits.run('nth:euler-totient(7)')).toEqual(6)
      expect(lits.run('nth:euler-totient(8)')).toEqual(4)
      expect(lits.run('nth:euler-totient(9)')).toEqual(6)
      expect(lits.run('nth:euler-totient(10)')).toEqual(4)
      expect(lits.run('nth:euler-totient(11)')).toEqual(10)
      expect(lits.run('nth:euler-totient(12)')).toEqual(4)
      expect(lits.run('nth:euler-totient(13)')).toEqual(12)
      expect(lits.run('nth:euler-totient(14)')).toEqual(6)
      expect(lits.run('nth:euler-totient(15)')).toEqual(8)
      expect(lits.run('nth:euler-totient(16)')).toEqual(8)
      expect(lits.run('nth:euler-totient(17)')).toEqual(16)
      expect(lits.run('nth:euler-totient(18)')).toEqual(6)
      expect(lits.run('nth:euler-totient(19)')).toEqual(18)
      expect(lits.run('nth:euler-totient(20)')).toEqual(8)
    })
  })

  describe('nth:mobius', () => {
    it('should return the mobius function of a number', () => {
      expect(lits.run('nth:mobius(1)')).toEqual(1)
      expect(lits.run('nth:mobius(2)')).toEqual(-1)
      expect(lits.run('nth:mobius(3)')).toEqual(-1)
      expect(lits.run('nth:mobius(4)')).toEqual(0)
      expect(lits.run('nth:mobius(5)')).toEqual(-1)
      expect(lits.run('nth:mobius(6)')).toEqual(1)
      expect(lits.run('nth:mobius(7)')).toEqual(-1)
      expect(lits.run('nth:mobius(8)')).toEqual(0)
      expect(lits.run('nth:mobius(9)')).toEqual(0)
      expect(lits.run('nth:mobius(10)')).toEqual(1)
      expect(lits.run('nth:mobius(11)')).toEqual(-1)
      expect(lits.run('nth:mobius(12)')).toEqual(0)
      expect(lits.run('nth:mobius(13)')).toEqual(-1)
      expect(lits.run('nth:mobius(14)')).toEqual(1)
      expect(lits.run('nth:mobius(15)')).toEqual(1)
      expect(lits.run('nth:mobius(16)')).toEqual(0)
      expect(lits.run('nth:mobius(17)')).toEqual(-1)
      expect(lits.run('nth:mobius(18)')).toEqual(0)
      expect(lits.run('nth:mobius(19)')).toEqual(-1)
      expect(lits.run('nth:mobius(20)')).toEqual(0)
      expect(lits.run('nth:mobius(21)')).toEqual(1)
      expect(lits.run('nth:mobius(22)')).toEqual(1)
      expect(lits.run('nth:mobius(23)')).toEqual(-1)
      expect(lits.run('nth:mobius(24)')).toEqual(0)
      expect(lits.run('nth:mobius(25)')).toEqual(0)
      expect(lits.run('nth:mobius(30)')).toEqual(-1)
      expect(lits.run('nth:möbius(42)')).toEqual(-1)
      expect(lits.run('nth:möbius(60)')).toEqual(0)
      expect(lits.run('nth:möbius(75)')).toEqual(0)
      expect(lits.run('nth:möbius(98)')).toEqual(0)
      expect(lits.run('nth:möbius(105)')).toEqual(-1)
      expect(lits.run('nth:möbius(210)')).toEqual(1)
      expect(lits.run('nth:möbius(997)')).toEqual(-1)
      expect(lits.run('nth:möbius(999)')).toEqual(0)
      expect(lits.run('nth:möbius(1000)')).toEqual(0)
      expect(lits.run('nth:möbius(2310)')).toEqual(-1)
      expect(lits.run('nth:möbius(30030)')).toEqual(1)
    })
  })
  describe('nth:mertens', () => {
    it('should return the mertens function of a number', () => {
      expect(lits.run('nth:mertens(1)')).toEqual(1)
      expect(lits.run('nth:mertens(2)')).toEqual(0)
      expect(lits.run('nth:mertens(3)')).toEqual(-1)
      expect(lits.run('nth:mertens(4)')).toEqual(-1)
      expect(lits.run('nth:mertens(5)')).toEqual(-2)
      expect(lits.run('nth:mertens(6)')).toEqual(-1)
      expect(lits.run('nth:mertens(7)')).toEqual(-2)
      expect(lits.run('nth:mertens(8)')).toEqual(-2)
      expect(lits.run('nth:mertens(9)')).toEqual(-2)
      expect(lits.run('nth:mertens(10)')).toEqual(-1)
      expect(lits.run('nth:mertens(11)')).toEqual(-2)
      expect(lits.run('nth:mertens(12)')).toEqual(-2)
      expect(lits.run('nth:mertens(13)')).toEqual(-3)
      expect(lits.run('nth:mertens(14)')).toEqual(-2)
      expect(lits.run('nth:mertens(15)')).toEqual(-1)
      expect(lits.run('nth:mertens(16)')).toEqual(-1)
      expect(lits.run('nth:mertens(17)')).toEqual(-2)
      expect(lits.run('nth:mertens(18)')).toEqual(-2)
      expect(lits.run('nth:mertens(19)')).toEqual(-3)
      expect(lits.run('nth:mertens(20)')).toEqual(-3)
      expect(lits.run('nth:mertens(21)')).toEqual(-2)
      expect(lits.run('nth:mertens(22)')).toEqual(-1)
      expect(lits.run('nth:mertens(23)')).toEqual(-2)
      expect(lits.run('nth:mertens(24)')).toEqual(-2)
      expect(lits.run('nth:mertens(25)')).toEqual(-2)
      expect(lits.run('nth:mertens(30)')).toEqual(-3)
      expect(lits.run('nth:mertens(42)')).toEqual(-2)
      expect(lits.run('nth:mertens(60)')).toEqual(-1)
      expect(lits.run('nth:mertens(75)')).toEqual(-3)
      expect(lits.run('nth:mertens(98)')).toEqual(1)
    })
  })
  describe('nth:sigma', () => {
    it('should return the sigma function of a number', () => {
      expect(lits.run('nth:sigma(1)')).toEqual(1)
      expect(lits.run('nth:sigma(2)')).toEqual(3)
      expect(lits.run('nth:sigma(3)')).toEqual(4)
      expect(lits.run('nth:sigma(4)')).toEqual(7)
      expect(lits.run('nth:sigma(5)')).toEqual(6)
      expect(lits.run('nth:sigma(6)')).toEqual(12)
      expect(lits.run('nth:sigma(7)')).toEqual(8)
      expect(lits.run('nth:sigma(8)')).toEqual(15)
      expect(lits.run('nth:sigma(9)')).toEqual(13)
      expect(lits.run('nth:sigma(10)')).toEqual(18)
      expect(lits.run('nth:sigma(11)')).toEqual(12)
      expect(lits.run('nth:sigma(12)')).toEqual(28)
      expect(lits.run('nth:sigma(13)')).toEqual(14)
      expect(lits.run('nth:sigma(14)')).toEqual(24)
      expect(lits.run('nth:sigma(15)')).toEqual(24)
      expect(lits.run('nth:sigma(16)')).toEqual(31)
      expect(lits.run('nth:sigma(17)')).toEqual(18)
      expect(lits.run('nth:sigma(18)')).toEqual(39)
      expect(lits.run('nth:sigma(19)')).toEqual(20)
      expect(lits.run('nth:sigma(20)')).toEqual(42)
    })
  })
  describe('nth:carmichael-lambda', () => {
    it('should return the carmichael lambda of a number', () => {
      expect(lits.run('nth:carmichael-lambda(1)')).toEqual(1)
      expect(lits.run('nth:carmichael-lambda(2)')).toEqual(1)
      expect(lits.run('nth:carmichael-lambda(3)')).toEqual(2)
      expect(lits.run('nth:carmichael-lambda(4)')).toEqual(2)
      expect(lits.run('nth:carmichael-lambda(5)')).toEqual(4)
      expect(lits.run('nth:carmichael-lambda(6)')).toEqual(2)
      expect(lits.run('nth:carmichael-lambda(7)')).toEqual(6)
      expect(lits.run('nth:carmichael-lambda(8)')).toEqual(2)
      expect(lits.run('nth:carmichael-lambda(9)')).toEqual(6)
      expect(lits.run('nth:carmichael-lambda(10)')).toEqual(4)
      expect(lits.run('nth:carmichael-lambda(11)')).toEqual(10)
      expect(lits.run('nth:carmichael-lambda(12)')).toEqual(2)
      expect(lits.run('nth:carmichael-lambda(13)')).toEqual(12)
      expect(lits.run('nth:carmichael-lambda(14)')).toEqual(6)
      expect(lits.run('nth:carmichael-lambda(15)')).toEqual(4)
      expect(lits.run('nth:carmichael-lambda(16)')).toEqual(4)
      expect(lits.run('nth:carmichael-lambda(17)')).toEqual(16)
    })
  })
  describe('cartesian-product', () => {
    it('should return the cartesian product of two or many lists', () => {
      expect(lits.run('nth:cartesian-product([1, 2], [3, 4])')).toEqual([[1, 3], [1, 4], [2, 3], [2, 4]])
      expect(lits.run('nth:cartesian-product([1, 2], [])')).toEqual([])
      expect(lits.run('nth:cartesian-product([], [3, 4])')).toEqual([])
      expect(lits.run('nth:cartesian-product([], [])')).toEqual([])
      expect(lits.run('nth:cartesian-product([1, 2], [3, 4], [5, 6])')).toEqual([[1, 3, 5], [1, 3, 6], [1, 4, 5], [1, 4, 6], [2, 3, 5], [2, 3, 6], [2, 4, 5], [2, 4, 6]])
    })
  })
  describe('nth:perfect-power', () => {
    it('should return tuple representing powers from number', () => {
      expect(lits.run('nth:perfect-power(1)')).toEqual([1, 2])
      expect(lits.run('nth:perfect-power(2)')).toEqual(null)
      expect(lits.run('nth:perfect-power(4)')).toEqual([2, 2])
      expect(lits.run('nth:perfect-power(8)')).toEqual([2, 3])
      expect(lits.run('nth:perfect-power(9)')).toEqual([3, 2])
      expect(lits.run('nth:perfect-power(16)')).toEqual([4, 2])
      expect(lits.run('nth:perfect-power(27)')).toEqual([3, 3])
      expect(lits.run('nth:perfect-power(32)')).toEqual([2, 5])
      expect(lits.run('nth:perfect-power(64)')).toEqual([8, 2])
      expect(lits.run('nth:perfect-power(81)')).toEqual([9, 2])
      expect(lits.run('nth:perfect-power(100)')).toEqual([10, 2])
      expect(lits.run('nth:perfect-power(121)')).toEqual([11, 2])
      expect(lits.run('nth:perfect-power(125)')).toEqual([5, 3])
      expect(lits.run('nth:perfect-power(128)')).toEqual([2, 7])
      expect(lits.run('nth:perfect-power(729)')).toEqual([27, 2])
      expect(lits.run('nth:perfect-power(1000)')).toEqual([10, 3])
      expect(lits.run('nth:perfect-power(1024)')).toEqual([32, 2])
      expect(lits.run('nth:perfect-power(1331)')).toEqual([11, 3])
      expect(lits.run('nth:perfect-power(4096)')).toEqual([64, 2])
      expect(lits.run('nth:perfect-power(6561)')).toEqual([81, 2])
    })
  })
  describe('nth:mod-exp', () => {
    it('should return the modular exponentiation of a number', () => {
      expect(lits.run('nth:mod-exp(2, 3, 1)')).toEqual(0)
      expect(lits.run('nth:mod-exp(2, 3, 5)')).toEqual(3)
      expect(lits.run('nth:mod-exp(3, 4, 7)')).toEqual(4)
      expect(lits.run('nth:mod-exp(5, 6, 11)')).toEqual(5)
      expect(lits.run('nth:mod-exp(7, 8, 13)')).toEqual(3)
      expect(lits.run('nth:mod-exp(9, 10, 17)')).toEqual(13)
      expect(lits.run('nth:mod-exp(11, 12, 19)')).toEqual(1)
      expect(lits.run('nth:mod-exp(13, 14, 23)')).toEqual(12)
      expect(lits.run('nth:mod-exp(15, 16, 29)')).toEqual(7)
      expect(lits.run('nth:mod-exp(4, 13, 497)')).toEqual(445)
    })
  })
  describe('nth:mod-inv', () => {
    it('should return the modular inverse of a number', () => {
      expect(lits.run('nth:mod-inv(2, 3)')).toEqual(2)
      expect(lits.run('nth:mod-inv(3, 7)')).toEqual(5)
      expect(lits.run('nth:mod-inv(4, 11)')).toEqual(3)
      expect(lits.run('nth:mod-inv(5, 13)')).toEqual(8)
      expect(lits.run('nth:mod-inv(6, 17)')).toEqual(3)
      expect(lits.run('nth:mod-inv(7, 19)')).toEqual(11)
      expect(lits.run('nth:mod-inv(8, 23)')).toEqual(3)
      expect(lits.run('nth:mod-inv(9, 29)')).toEqual(13)
      expect(() => lits.run('nth:mod-inv(4, 6)')).toThrow()
    })
  })
  describe('extended-gcd', () => {
    it('should return the extended gcd of two numbers', () => {
      expect(lits.run('nth:extended-gcd(1, 1)')).toEqual([1, 0, 1])
      expect(lits.run('nth:extended-gcd(2, 3)')).toEqual([1, -1, 1])
      expect(lits.run('nth:extended-gcd(4, 6)')).toEqual([2, -1, 1])
      expect(lits.run('nth:extended-gcd(8, 12)')).toEqual([4, -1, 1])
      expect(lits.run('nth:extended-gcd(10, 15)')).toEqual([5, -1, 1])
      expect(lits.run('nth:extended-gcd(100, 200)')).toEqual([100, 1, 0])
    })
  })
  describe('nth:chinese-remainder', () => {
    it('should return the chinese remainder of a list of numbers', () => {
      expect(lits.run('nth:chinese-remainder([2, 3], [3, 5])')).toEqual(8)
      expect(lits.run('nth:chinese-remainder([2, 3], [3, 5])')).toEqual(8)
      expect(lits.run('nth:chinese-remainder([1, 2, 3], [2, 3, 5])')).toEqual(23)
      expect(() => lits.run('nth:chinese-remainder([1, 2, 4], [2, 3, 6])')).toThrow(LitsError)
      expect(() => lits.run('nth:chinese-remainder([1, 2], [2, 3, 5])')).toThrow()
    })
  })
  describe('nth:stirling-first', () => {
    it('should return the stirling number of the first kind', () => {
      expect(lits.run('nth:stirling-first(1, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-first(2, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-first(2, 2)')).toEqual(1)
      expect(lits.run('nth:stirling-first(3, 1)')).toEqual(2)
      expect(lits.run('nth:stirling-first(3, 2)')).toEqual(3)
      expect(lits.run('nth:stirling-first(3, 3)')).toEqual(1)
      expect(lits.run('nth:stirling-first(4, 1)')).toEqual(6)
      expect(lits.run('nth:stirling-first(4, 2)')).toEqual(11)
      expect(lits.run('nth:stirling-first(4, 3)')).toEqual(6)
      expect(lits.run('nth:stirling-first(4, 4)')).toEqual(1)
      expect(() => lits.run('nth:stirling-first(4, 5)')).toThrow()
      expect(() => lits.run('nth:stirling-first(4, 0)')).toThrow()
      expect(() => lits.run('nth:stirling-first(0, 0)')).toThrow()
    })
  })
  describe('nth:stirling-second', () => {
    it('should return the stirling number of the second kind', () => {
      expect(lits.run('nth:stirling-second(1, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-second(2, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-second(2, 2)')).toEqual(1)
      expect(lits.run('nth:stirling-second(3, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-second(3, 2)')).toEqual(3)
      expect(lits.run('nth:stirling-second(3, 3)')).toEqual(1)
      expect(lits.run('nth:stirling-second(4, 1)')).toEqual(1)
      expect(lits.run('nth:stirling-second(4, 2)')).toEqual(7)
      expect(lits.run('nth:stirling-second(4, 3)')).toEqual(6)
      expect(lits.run('nth:stirling-second(4, 4)')).toEqual(1)
      expect(() => lits.run('nth:stirling-first(4, 5)')).toThrow()
      expect(() => lits.run('nth:stirling-first(4, 0)')).toThrow()
      expect(() => lits.run('nth:stirling-first(0, 0)')).toThrow()
    })
  })
})
